name: "Airport Checkin"

on:
  schedule:
    - cron: "30 22 * * *"  # scheduled at 06:30 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-20.04  # 改为 Ubuntu 20.04，对 Python 3.7 支持更好
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v4  # 升级到最新版本
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v4  # 升级到 v4 版本
        with:
          python-version: '3.7'  # 保持 3.7，但使用字符串格式

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-100 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sign
        env:
          SCKEY: ${{ secrets.SCKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
        run: |
          python3 ./main.py
